### ISSUE TITLE
Allow changing the image used for build summary generation

### ISSUE THREAD

**Issue by pagelypete** [docker/actions-toolkit#407]
Is it possible to allow changing the image, or at least specifying a prefix that isn't `docker.io` for the build summary generation image? We have a lot of GitHub Actions runners in AWS but they are behind a NAT instance so they share a single IP address. We have a pull through cache that we use so that we aren't hitting Docker Hub super frequently and using up precious pull quota, but this summary feature unfortunately always pulls an image from Docker Hub so we had to turn it off.

If we could provide our own image to pull then we could still use the feature.

Thanks!

**Comment by crazy-max** [comment]
Should be fixed with https://github.com/docker/actions-toolkit/pull/410 using `DOCKER_BUILD_EXPORT_BUILD_IMAGE` en var:

```yaml
name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: user/app:latest
        env:
          DOCKER_BUILD_EXPORT_BUILD_IMAGE: dockereng/export-build:latest
```
